In [56]:
#import necessary libraries

import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import html5lib
import sys
reload(sys)

In [57]:
# create an empty DataFrame to append draftees to
draftees_dframe = pd.DataFrame()
sys.setdefaultencoding('utf-8')

In [58]:
dframe = pd.io.html.read_html("http://www.basketball-reference.com/draft/NBA_2018.html")
dframe = dframe[0]
draftees_dframe = draftees_dframe.append(dframe, ignore_index=True)
draftees_dframe

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Round 1,Unnamed: 4_level_0,Totals,Shooting,Per Game,Advanced,Unnamed: 9_level_0,...,Unnamed: 12_level_0,Unnamed: 13_level_0,Unnamed: 14_level_0,Unnamed: 15_level_0,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0
,Rk,Pk,Tm,Player,College,Yrs,G,MP,PTS,TRB,...,3P%,FT%,MP,PTS,TRB,AST,WS,WS/48,BPM,VORP
0,1,1,PHO,Deandre Ayton,University of Arizona,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,SAC,Marvin Bagley,Duke University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,ATL,Luka Doncic,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,MEM,Jaren Jackson,Michigan State University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,DAL,Trae Young,University of Oklahoma,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,6,ORL,Mohamed Bamba,University of Texas at Austin,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,7,CHI,Wendell Carter,Duke University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,8,CLE,Collin Sexton,University of Alabama,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,9,NYK,Kevin Knox,University of Kentucky,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,10,PHI,Mikal Bridges,Villanova University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,11,CHO,Shai Gilgeous-Alexander,University of Kentucky,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,12,LAC,Miles Bridges,Michigan State University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,13,LAC,Jerome Robinson,Boston College,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,14,DEN,Michael Porter,University of Missouri,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,15,WAS,Troy Brown,University of Oregon,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,16,PHO,Zhaire Smith,Texas Tech University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,17,MIL,Donte DiVincenzo,Villanova University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,18,SAS,Lonnie Walker,University of Miami,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,19,ATL,Kevin Huerter,University of Maryland,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,20,MIN,Josh Okogie,Georgia Institute of Technology,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,21,UTA,Grayson Allen,Duke University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,22,CHI,Chandler Hutchison,Boise State University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,23,IND,Aaron Holiday,"University of California, Los Angeles",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,24,POR,Anfernee Simons,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,25,LAL,Moritz Wagner,University of Michigan,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,26,PHI,Landry Shamet,Wichita State University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,27,BOS,Robert Williams,Texas A&M University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,28,GSW,Jacob Evans,University of Cincinnati,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,29,BRK,Dzanan Musa,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,30,ATL,Omari Spellman,Villanova University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,31,31,PHO,Elie Okobo,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,32,32,MEM,Jevon Carter,West Virginia University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,33,33,DAL,Jalen Brunson,Villanova University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,34,34,ATL,Devonte' Graham,University of Kansas,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,35,35,ORL,Melvin Frazier,Tulane University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,36,36,NYK,Mitchell Robinson,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,37,37,SAC,Gary Trent,Duke University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,38,38,PHI,Khyri Thomas,Creighton University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,39,39,PHI,Isaac Bonga,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,40,40,BRK,Rodions Kurucs,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,41,41,ORL,Jarred Vanderbilt,University of Kentucky,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,42,42,DET,Bruce Brown,University of Miami,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,43,43,DEN,Justin Jackson,University of Maryland,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,44,44,WAS,Issuf Sanon,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,45,45,BRK,Hamidou Diallo,University of Kentucky,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,46,46,HOU,De'Anthony Melton,University of Southern California,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,47,47,LAL,Sviatoslav Mykhailiuk,University of Kansas,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,48,48,MIN,Keita Bates-Diop,Ohio State University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,49,49,SAS,Chimezie Metu,University of Southern California,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,50,50,IND,Alize Johnson,Missouri State,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,51,51,NOP,Tony Carr,Pennsylvania State University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,52,52,UTA,Vince Edwards,Purdue University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,53,53,OKC,Devon Hall,University of Virginia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,54,54,DAL,Shake Milton,Southern Methodist University,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,55,55,CHO,Arnoldas Kulboka,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,56,56,PHI,Ray Spalding,University of Louisville,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,57,57,OKC,Kevin Hervey,University of Texas at Arlington,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,58,58,DEN,Thomas Welsh,"University of California, Los Angeles",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,59,59,PHO,George King,University of Colorado,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,60,60,PHI,Kostas Antetokounmpo,University of Dayton,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
draftees_dframe = draftees_dframe.ix[:, 3:5]

                    Round 1                     Unnamed: 4_level_0
                     Player                                College
0             Deandre Ayton                  University of Arizona
1             Marvin Bagley                        Duke University
2               Luka Doncic                                    NaN
3             Jaren Jackson              Michigan State University
4                Trae Young                 University of Oklahoma
5             Mohamed Bamba          University of Texas at Austin
6            Wendell Carter                        Duke University
7             Collin Sexton                  University of Alabama
8                Kevin Knox                 University of Kentucky
9             Mikal Bridges                   Villanova University
10  Shai Gilgeous-Alexander                 University of Kentucky
11            Miles Bridges              Michigan State University
12          Jerome Robinson                         Boston College
13           Michael Porter                 University of Missouri
14               Troy Brown                   University of Oregon
15             Zhaire Smith                  Texas Tech University
16         Donte DiVincenzo                   Villanova University
17            Lonnie Walker                    University of Miami
18            Kevin Huerter                 University of Maryland
19              Josh Okogie        Georgia Institute of Technology
20            Grayson Allen                        Duke University
21       Chandler Hutchison                 Boise State University
22            Aaron Holiday  University of California, Los Angeles
23          Anfernee Simons                                    NaN
24            Moritz Wagner                 University of Michigan
25            Landry Shamet               Wichita State University
26          Robert Williams                   Texas A&M University
27              Jacob Evans               University of Cincinnati
28              Dzanan Musa                                    NaN
29           Omari Spellman                   Villanova University
..                      ...                                    ...
32               Elie Okobo                                    NaN
33             Jevon Carter               West Virginia University
34            Jalen Brunson                   Villanova University
35          Devonte' Graham                   University of Kansas
36           Melvin Frazier                      Tulane University
37        Mitchell Robinson                                    NaN
38               Gary Trent                        Duke University
39             Khyri Thomas                   Creighton University
40              Isaac Bonga                                    NaN
41           Rodions Kurucs                                    NaN
42        Jarred Vanderbilt                 University of Kentucky
43              Bruce Brown                    University of Miami
44           Justin Jackson                 University of Maryland
45              Issuf Sanon                                    NaN
46           Hamidou Diallo                 University of Kentucky
47        De'Anthony Melton      University of Southern California
48    Sviatoslav Mykhailiuk                   University of Kansas
49         Keita Bates-Diop                  Ohio State University
50            Chimezie Metu      University of Southern California
51            Alize Johnson                         Missouri State
52                Tony Carr          Pennsylvania State University
53            Vince Edwards                      Purdue University
54               Devon Hall                 University of Virginia
55             Shake Milton          Southern Methodist University
56         Arnoldas Kulboka                                    NaN
57             Ray Spalding               University of Louisville
58             Kevin Hervey       University of Texas at Arlington
59             Thomas Welsh  University of California, Los Angeles
60              George King                 University of Colorado
61     Kostas Antetokounmpo                   University of Dayton

[62 rows x 2 columns]

In [61]:
draftees_dframe .columns = ['Player', 'College']
draftees_dframe

                     Player                                College
0             Deandre Ayton                  University of Arizona
1             Marvin Bagley                        Duke University
2               Luka Doncic                                    NaN
3             Jaren Jackson              Michigan State University
4                Trae Young                 University of Oklahoma
5             Mohamed Bamba          University of Texas at Austin
6            Wendell Carter                        Duke University
7             Collin Sexton                  University of Alabama
8                Kevin Knox                 University of Kentucky
9             Mikal Bridges                   Villanova University
10  Shai Gilgeous-Alexander                 University of Kentucky
11            Miles Bridges              Michigan State University
12          Jerome Robinson                         Boston College
13           Michael Porter                 University of Missouri
14               Troy Brown                   University of Oregon
15             Zhaire Smith                  Texas Tech University
16         Donte DiVincenzo                   Villanova University
17            Lonnie Walker                    University of Miami
18            Kevin Huerter                 University of Maryland
19              Josh Okogie        Georgia Institute of Technology
20            Grayson Allen                        Duke University
21       Chandler Hutchison                 Boise State University
22            Aaron Holiday  University of California, Los Angeles
23          Anfernee Simons                                    NaN
24            Moritz Wagner                 University of Michigan
25            Landry Shamet               Wichita State University
26          Robert Williams                   Texas A&M University
27              Jacob Evans               University of Cincinnati
28              Dzanan Musa                                    NaN
29           Omari Spellman                   Villanova University
..                      ...                                    ...
32               Elie Okobo                                    NaN
33             Jevon Carter               West Virginia University
34            Jalen Brunson                   Villanova University
35          Devonte' Graham                   University of Kansas
36           Melvin Frazier                      Tulane University
37        Mitchell Robinson                                    NaN
38               Gary Trent                        Duke University
39             Khyri Thomas                   Creighton University
40              Isaac Bonga                                    NaN
41           Rodions Kurucs                                    NaN
42        Jarred Vanderbilt                 University of Kentucky
43              Bruce Brown                    University of Miami
44           Justin Jackson                 University of Maryland
45              Issuf Sanon                                    NaN
46           Hamidou Diallo                 University of Kentucky
47        De'Anthony Melton      University of Southern California
48    Sviatoslav Mykhailiuk                   University of Kansas
49         Keita Bates-Diop                  Ohio State University
50            Chimezie Metu      University of Southern California
51            Alize Johnson                         Missouri State
52                Tony Carr          Pennsylvania State University
53            Vince Edwards                      Purdue University
54               Devon Hall                 University of Virginia
55             Shake Milton          Southern Methodist University
56         Arnoldas Kulboka                                    NaN
57             Ray Spalding               University of Louisville
58             Kevin Hervey       University of Texas at Arlington
59             Thomas Welsh  University of California, Los Angeles
60              George King                 University of Colorado
61     Kostas Antetokounmpo                   University of Dayton

[62 rows x 2 columns]

In [64]:
draftees_dframe = draftees_dframe[draftees_dframe['College'].notnull()]
draftees_dframe = draftees_dframe[draftees_dframe['Player'] != 'Player']

In [66]:
draftees_dframe.head()

          Player                        College
0  Deandre Ayton          University of Arizona
1  Marvin Bagley                Duke University
3  Jaren Jackson      Michigan State University
4     Trae Young         University of Oklahoma
5  Mohamed Bamba  University of Texas at Austin

In [ ]:
#3P%, FT%, 3PA,